---
- name: Install required packages
  yum: >
    name={{ item }}
    state=installed
  with_items:
    - python2-pip

- name: Install supervisor via pip
  pip: >
    name=supervisor
    state=present

- name: Create supervisord user group
  group: >
    name={{ supervisord_user_group }}
    state=present

- name: Create supervisord user
  user: >
    name={{ supervisord_user }}
    group={{ supervisord_user_group }}
    createhome=no
    state=present

- name: Create supervisord log directory
  file: >
    path={{ supervisord_log_dir }}
    state=directory
    owner={{ supervisord_user }}
    group={{ supervisord_user_group }}
    mode=0775

- name: Create supervisord configuration directories
  file: >
    path={{ item }}
    state=directory
    owner={{ supervisord_user }}
    group={{ supervisord_user_group }}
    mode=0775
  with_items:
    - "{{ supervisord_config_dir }}"
    - "{{ supervisord_config_dir }}/conf.d"

- name: Deploy supervisord configuration file
  template: >
    src=supervisord.conf.tpl
    dest={{ supervisord_config_dir }}/supervisord.conf
    owner=root
    group=root
    mode=0644

- name: Install supervisord systemd script
  template: >
    src=supervisord.service.tpl
    dest=/etc/systemd/system/supervisord.service
    owner=root
    group=root
    mode=0755

- name: Start and enable supervisord daemon
  systemd: >
    name=supervisord
    state=started
    enabled=yes
    daemon_reload=yes
